# Generated by Django 4.2.10 on 2024-04-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0005_aplication_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="aplication_users",
            name="contraseña",
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aplication_users",
            name="Name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="locations",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="domo_api.aplication_users",
            ),
        ),
    ]
